// tslint:disable:max-line-length
import {assert} from "chai";
import {Annotation} from "./annotation";
import {renderToString} from "./html";

describe("renderToString", () => {

  it("Returns text directly with no annotations", () => {
    assert.equal(renderToString("Foo", [], {autoParagraph: false}), "Foo");
  });

  it("Returns auto-generated paragraph breaks by default", () => {
    assert.equal(renderToString("Foo\nBar", []),
`<p class=\"sharpie-annotation sharpie-id-0 auto-para-break\">Foo</p><p class=\"sharpie-annotation sharpie-id-1 auto-para-break\">
Bar</p>`);
  });

  it("Returns custom markup annotations", () => {
    const atns: Annotation[] = [
      {start: 1, end: 5, type: "markup", format: {color: "blue"}},
    ];
    assert.equal(renderToString("Testing annotation", atns, {autoParagraph: false}),
`T<span style=\"color: blue;\" class=\"sharpie-annotation sharpie-id-0\">esti</span>ng annotation`);
  });

  it("Correctly closes and reopens overlapping markup annotations", () => {
    const atns: Annotation[] = [
      {start: 1, end: 5, type: "markup", format: {color: "blue"}},
      {start: 3, end: 9, type: "markup", format: {bgColor: "green"}},
    ];
    assert.equal(renderToString("Testing annotation", atns, {autoParagraph: false}),
`T<span style=\"color: blue;\" class=\"sharpie-annotation sharpie-id-0\">es<span style=\"background-color: green;\" class=\"sharpie-annotation sharpie-id-1\">ti</span></span><span style=\"background-color: green;\" class=\"sharpie-annotation sharpie-id-1\">ng a</span>nnotation`);
  });

  it("Handles complicated stacks of overlapping and autogenerated markup annotations", () => {
    const atns: Annotation[] = [
      {start: 1, end: 10, type: "markup", format: {color: "blue"}},
      {start: 5, end: 6, type: "markup", meta: {htmlTagName: "em"}},
      {start: 5, end: 15, type: "markup", format: {bgColor: "green"}},
      {start: 3, end: 25, type: "markup", format: {opacity: 0.5}},
      {start: 14, end: 25, type: "markup", meta: {htmlTagName: "strong", htmlClassName: "test"}},
    ];
    const str = `This test checks that

the renderer can handle
complicated

stacks of custom annotations and auto-generated

paragraph annotations.`;

    assert.equal(renderToString(str, atns),
`<p class="sharpie-annotation sharpie-id-0 auto-para-break">T<span style="color: blue;" class="sharpie-annotation sharpie-id-1">hi<span style="opacity: 0.5;" class="sharpie-annotation sharpie-id-2">s <span style="background-color: green;" class="sharpie-annotation sharpie-id-3"><em class="sharpie-annotation sharpie-id-4">t</em>est </span></span></span><span style="opacity: 0.5;" class="sharpie-annotation sharpie-id-2"><span style="background-color: green;" class="sharpie-annotation sharpie-id-3">chec<strong class="sharpie-annotation sharpie-id-5 test">k</strong></span><strong class="sharpie-annotation sharpie-id-5 test">s that</strong></span></p><p class="sharpie-annotation sharpie-id-6 auto-para-break"><span style="opacity: 0.5;" class="sharpie-annotation sharpie-id-2"><strong class="sharpie-annotation sharpie-id-5 test">
</strong></span></p><p class="sharpie-annotation sharpie-id-7 auto-para-break"><span style="opacity: 0.5;" class="sharpie-annotation sharpie-id-2"><strong class="sharpie-annotation sharpie-id-5 test">
th</strong></span>e renderer can handle</p><p class="sharpie-annotation sharpie-id-8 auto-para-break">
complicated</p><p class="sharpie-annotation sharpie-id-9 auto-para-break">
</p><p class="sharpie-annotation sharpie-id-10 auto-para-break">
stacks of custom annotations and auto-generated</p><p class="sharpie-annotation sharpie-id-11 auto-para-break">
</p><p class="sharpie-annotation sharpie-id-12 auto-para-break">
paragraph annotations.</p>`);
  });

});
